repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.3
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.5.24
  hooks:
    - id: uv-lock
- repo: local
  hooks:
    - id: compile-schema
      name: compile-schema
      language: system
      entry: uv run ./scripts/compile_schema.py
      always_run: true
- repo: local
  hooks:
    - id: compile-docs
      name: compile-docs
      language: system
      entry: uv run --extra docs ./scripts/compile_docs.py
      always_run: true
