site_name: Schéma data·inclusion
site_url: https://gip-inclusion.github.io/data-inclusion-schema/

repo_name: gip-inclusion/data-inclusion-schema
repo_url: https://github.com/gip-inclusion/data-inclusion-schema

theme:
  name: material
  logo: assets/DataInclusion-Monogramme-Blanc.png
  favicon: assets/DataInclusion-Monogramme-Couleur.png

nav:
  - Accueil: index.md
  - Structure: structure.md
  - Service: service.md
  - Référentiels:
    - Frais: referentiels/frais.md
    - Labels nationaux: referentiels/labels_nationaux.md
    - Modes d’accueil: referentiels/modes_accueil.md
    - Modes de mobilisation: referentiels/modes_mobilisation.md
    - Personnes mobilisatrices: referentiels/personnes_mobilisatrices.md
    - Profils: referentiels/profils.md
    - Thématiques: referentiels/thematiques.md
    - Typologies de services: referentiels/typologies_de_services.md
    - Typologies de structures: referentiels/typologies_de_structures.md
    - Zones de diffusion: referentiels/zones_de_diffusion_types.md

markdown_extensions:
  - pymdownx.superfences
  - admonition

extra:
  version:
    provider: mike
