site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
nav:
  - Home: index.md
  - Service: service.md
  - Service2: service2.md
  - Service3: service3.md
  - Structure: structure.md
  - Test: test.md
  - JinjaTest: jinja_test.md
plugins:
- search
- mkdocstrings
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde