site_name: Schéma data·inclusion
site_url: https://gip-inclusion.github.io/data-inclusion-schema/

repo_name: gip-inclusion/data-inclusion-schema
repo_url: https://github.com/gip-inclusion/data-inclusion-schema

theme:
  name: material
  language: fr
  logo: assets/DataInclusion-Monogramme-Blanc.png
  favicon: assets/DataInclusion-Monogramme-Couleur.png

markdown_extensions:
  - pymdownx.superfences
  - admonition

plugins:
  - literate-nav:
      nav_file: summary.md
  - search

extra:
  version:
    provider: mike
