name: docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --frozen --group docs

      - if: github.ref == 'refs/heads/main'
        run: uv run mike deploy dev --push

      - if: startsWith(github.ref, 'refs/tags/v0')
        run: uv run mike deploy ${{ github.ref_name }} latest --push --update-aliases

      - if: startsWith(github.ref, 'refs/tags/v1')
        run: uv run mike deploy ${{ github.ref_name }} --push
