name: docs

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
      - run: uv sync --frozen --group docs

      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - if: github.event_name == 'pull_request'
        run: uv run mike deploy dev --push

      - if: startsWith(github.ref, 'refs/tags/v0')
        run: uv run mike deploy ${{ github.ref_name }} latest --push --update-aliases

      - if: startsWith(github.ref, 'refs/tags/v1')
        run: uv run mike deploy ${{ github.ref_name }} --push
